baseURL = 'https://fsfam.club/resources'
canonifyurls = true
languageCode = 'en-us'
title = 'Fullspeed Resources'
theme = "hugo-relearn-theme"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
editURL = "https://github.com/Fullspeed-Family/fullspeed-resources/edit/main/content/"
showVisitedLinks = false
disableLanguageSwitchingButton = true
themeVariant = "fsf"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-discord'></i> FSFam Discord"
identifier = "ds"
url = "https://discord.gg/dxMjG732ZY"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "appendix/credits/"
weight = 30